{% set version = "0.7.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tarchetypes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tarchetypes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tarchetypes/tarchetypes_{{ version }}.tar.gz
  sha256: fab8a9623cc901147ab725977440d9310cb6db994dfc01f068dd4f9c4625e3f9

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-digest >=0.6.25
    - r-dplyr >=1.0.0
    - r-fs >=1.4.2
    - r-furrr >=0.3.0
    - r-future >=1.0.0
    - r-future.callr >=0.2.0
    - r-rlang >=0.4.7
    - r-targets >=0.14.0
    - r-tibble >=3.0.1
    - r-tidyselect >=1.1.0
    - r-vctrs >=0.3.4
    - r-withr >=2.1.2
  run:
    - r-base
    - r-digest >=0.6.25
    - r-dplyr >=1.0.0
    - r-fs >=1.4.2
    - r-furrr >=0.3.0
    - r-future >=1.0.0
    - r-future.callr >=0.2.0
    - r-rlang >=0.4.7
    - r-targets >=0.14.0
    - r-tibble >=3.0.1
    - r-tidyselect >=1.1.0
    - r-vctrs >=0.3.4
    - r-withr >=2.1.2

test:
  commands:
    - $R -e "library('tarchetypes')"           # [not win]
    - "\"%R%\" -e \"library('tarchetypes')\""  # [win]

about:
  home: https://docs.ropensci.org/tarchetypes/
  dev_url: https://github.com/ropensci/tarchetypes
  license: MIT
  summary: Function-oriented Make-like declarative workflows for Statistics and data science are supported in the 'targets' R package. As an extension to 'targets', the 'tarchetypes' package provides convenient user-side functions to make 'targets' easier to use. By establishing reusable archetypes for common kinds of targets
    and pipelines, these functions help express complicated reproducible workflows concisely and compactly. The methods in this package were influenced by the 'drake' R package by Will Landau (2018) <doi:10.21105/joss.00550>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf
    - wlandau
